[package]
name = "Shrinkr"
version = "0.1.0"
edition = "2021"
description = "a compression tool for files and folders"
license = "MIT"
repository = "https://github.com/amrtamer23/gust" 


[dependencies]
flate2 = "1.0"
tar = "0.4.43"



